
[workspace]
resolver = '2'
members = [
	'lib/rust/mediatr',
	'apps/rust/prutaj_board',
	'lib/rust/surrealdb_extensions',
]

[workspace.dependencies.actix-web]
version = '4.14.0'

[workspace.dependencies.chrono]
version = '0.4.45'

[workspace.dependencies.surrealdb]
version = '3.2.1'
features = ['kv-rocksdb']

[workspace.dependencies.serde]
version = '1.0.229'

[workspace.dependencies.ulid]
version = '3.0.0'

[workspace.dependencies.dotenvy]
version = '0.15.7'

[workspace.dependencies.utoipa]
version = '5.4.0'
features = ['yaml', 'actix_extras', 'chrono']

[patch.crates-io]
diskann-wide = { path = 'vendor/diskann-wide' }

[profile.release]
lto = true
