
[workspace]
resolver = '2'
members = [
	'lib/rust/mediatr',
	'apps/rust/prutaj_board',
	'lib/rust/surrealdb_extensions',
	'lib/rust/macros/derive/macros_abstraction',
	'lib/rust/macros/derive/macros_derive',
	'lib/rust/macros/security/macros_security',
	'lib/rust/macros/security/macros_security_core',
	'lib/rust/pass_me',
	'lib/rust/pass_me_core',
	'lib/rust/pass_me_macros',
]

[workspace.dependencies.actix-web]
version = '4.14.1'

[workspace.dependencies.chrono]
version = '0.4.45'

[workspace.dependencies.surrealdb]
version = '3.2.4'
features = ['kv-rocksdb']

[workspace.dependencies.serde]
version = '1.0.229'

[workspace.dependencies.serde_json]
version = '1.0.151'

[workspace.dependencies.ulid]
version = '3.0.0'

[workspace.dependencies.dotenvy]
version = '0.15.7'

[workspace.dependencies.utoipa]
version = '5.5.0'
features = ['yaml', 'actix_extras', 'chrono']

[workspace.dependencies.quote]
version = '1.0.47'

[workspace.dependencies.syn]
version = '3.0.3'

[workspace.dependencies.proc-macro2]
version = '1.0.107'

[workspace.dependencies.darling]
version = '0.24.1'

[workspace.dependencies.env_logger]
version = '0.11.11'

[workspace.dependencies.zitadel]
version = '5.7.7'
features = ['actix']

[workspace.dependencies.reqwest]
version = '0.12.12'

[patch.crates-io]
diskann-wide = { path = 'vendor/diskann-wide' }

[profile.release]
lto = true
