[package]
name = "prutaj_board"
version = "0.1.0"
edition = "2021"
default-run = "prutaj_board"

[dependencies]
mediatr = { path = "../../../lib/rust/mediatr" }
surrealdb_extensions = { path = "../../../lib/rust/surrealdb_extensions" }
macros_abstraction = { path = "../../../lib/rust/macros_abstraction" }
macros_derive = { path = "../../../lib/rust/macros_derive" }

[dependencies.actix-web]
workspace = true

[dependencies.chrono]
workspace = true

[dependencies.surrealdb]
workspace = true
features = ["kv-rocksdb"]

[dependencies.serde]
workspace = true

[dependencies.ulid]
workspace = true

[dependencies.dotenvy]
workspace = true

[dependencies.utoipa]
workspace = true

[dependencies.env_logger]
workspace = true

[[bin]]
name = "generate_openapi"
path = "src/bin/generate_openapi.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
